version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 8501:8501
    volumes:
      - "/storage/syncthing/L2_good_to_have/:/input"
    deploy:
      restart_policy:
        condition: on-failure
