version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 8501:8501
    volumes:
      - .:/workdir
      - "/storage/syncthing/tchen-homes/tchen/Photos:/input"
    deploy:
      restart_policy:
        condition: on-failure
      # uncomment the following for gpu
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
